replicaCount: 1

image:
  repository: docker.io/hossamalsankary/coder
  tag: 'latest'
  pullPolicy: Always

# Specifies one or more secrets to be used when pulling images from a
# private container repository
imagePullSecrets: []
#  - name: registry-creds

nameOverride: ""
fullnameOverride: ""
hostnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
priorityClassName: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: ""
      paths:
        - /
  ingressClassName: ""
  #tls:
  #  - secretName: code-server
  #    hosts:
  #      - code-server.example.loc

# Optional additional arguments
extraArgs: []
  # These are the arguments normally passed to code-server; run
  # code-server --help for a list of available options.

# Optional additional environment variables
extraVars:
  - name: DOCKER_HOST
    value: unix:///var/run/docker.sock

volumePermissions:
  enabled: true
  securityContext:
    runAsUser: 0

securityContext:
  enabled: true
  fsGroup: 0
  runAsUser: 0

resources: 
  requests:
    cpu: 200m
    memory: 1000Mi

affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  annotations: {}
  # existingClaim: ""
  # hostPath: /data

extraVolumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock
      type: Socket

extraVolumeMounts: 
  - name: docker
    mountPath: /var/run/docker.sock
    readOnly: false

lifecycle:
  enabled: false
  # postStart:
  #  exec:
  #    command:
  #      - /bin/bash
  #      - -c
  #      - curl -s -L SOME_SCRIPT | bash

extraContainers: |
# If docker-dind is used, DOCKER_HOST env is mandatory to set in "extraVars"
#- name: docker-dind
#  image: docker:19.03-dind
#  imagePullPolicy: IfNotPresent
#  resources:
#    requests:
#      cpu: 250m
#      memory: 256M
#  securityContext:
#    privileged: true
#    procMount: Default
#  env:
#  - name: DOCKER_TLS_CERTDIR
#    value: ""
#  - name: DOCKER_DRIVER
#    value: "overlay2"

extraInitContainers: |
  - name: customization
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: IfNotPresent
    env:
      - name: SERVICE_URL
        value: https://open-vsx.org/vscode/gallery
      - name: ITEM_URL
        value: https://open-vsx.org/vscode/item
    command:
      - sh
      - -c
      - |
        code-server --install-extension ms-python.python
        code-server --install-extension golang.Go
        code-server --install-extension hashicorp.terraform  
        code-server --install-extension ms-azuretools.vscode-docker
        code-server --install-extension streetsidesoftware.code-spell-checker 
        code-server --install-extension timonwong.shellcheck
    volumeMounts:
      - name: data
        mountPath: /home/coder

extraSecretMounts: []
extraConfigmapMounts: []
extraPorts: []
